### PR TITLE
Fixed outdated SDK version crash

### LINKED ISSUE #28: Outdated SDK version causing Expo to crash
FIX: https://github.com/scorelab/Massa/pull/27

Steps to Reproduce:

STEP 1: Clone Massa
STEP 2: Navigate into Massa (cd Massa)
STEP 3: Install necessary packages (npm install)
STEP 4: Run the android app (react-native run-android)
STEP 5: Meet the crash

Here is how the crash looks

screenshot_2018-11-04-14-31-26-177_host exp exponent

Find this task on my website: http://itsrohan.com/gci/gcitasks

### PR DESCRIPTION
**Pull request by angeryrohan**
Fixes: #28 

After running the cloned files, we run into this crash, provided by expo.

screenshot_2018-11-04-14-31-26-177_host exp exponent

This PR fixes this error by upgrading the libraries accordingly. Here is a screenshot of successful build after updating the libraries. 

screenshot_2018-11-04-14-46-29-313_host exp exponent

### CODE REVIEW

**Review by championpaddler — CHANGES_REQUESTED** [review]
@rohancl  Fix the code check.

**Review by JaDogg — CHANGES_REQUESTED** [review]
Create a .gitignore, get rid of all the node_modules files.

**Comment by rohancl** [comment]
@JaDogg @sk9331657 I think i have made the appropriate connections. Please review. :)

**Review by JaDogg — APPROVED** [review]
Nice. 💯 @rohancl Let's see what @sk9331657 and others says as well. 👍

**Comment by iammosespaulr** [comment]
@scorelab/massa-maintainers this just created ... a whole load of reverts and ... commits for changes in 3 files ...

**Comment by angeryrohan** [comment]
I'm sorry, I should have squashed my commits :/

**Pull request merged**
